services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-nexus}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DB:/docker-entrypoint-initdb.d
    ports:
      - "0.0.0.0:${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Nexus
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-nexus}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "0.0.0.0:${BACKEND_PORT:-8080}:8080"
    volumes:
      - nexus_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        # Troque localhost pelo IP do computador servidor
        VITE_API_URL: http://192.168.0.137:8080
    ports:
      - "0.0.0.0:${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  nexus_uploads:
